CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATOGORY_ID TEXT,
    UNIT_TEXT,
    PRICE_REAL
);


INSERT INTO PRODUCTS (PRODUCT_ID,PRODUCT_NAME,SUPPLIER_ID,CATOGORY_ID,UNIT_TEXT,PRICE_REAL)
VALUES
('1','Chais','1','1','10 boxes*20 Bags', 18),
('2','Chang','1','1','24-12 OZ Bottles',19),
('3','ANISEED SYRUP','1','2','12-550 ml bottles',10),
('4','Chef Anton Seasoning','2','2','48-6 OZ Jars',22),
('5','Chef Anton Mix','2','2','36 Boxes',21.35);

SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;

SELECT AVG(PRICE) AS Average_Price
FROM PRODUCTS;

SELECT SUM(PRICE) AS Total_Price
FROM PRODUCTS;
DROP TABLE PRODUCTS